services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin_password}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL:-mongodb://root:admin_password@mongo:27017/}
      ME_CONFIG_BASICAUTH_ENABLED: ${ME_CONFIG_BASICAUTH_ENABLED:-true}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-mongo_express_user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-mongo_express_password}

  discord-bot:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: dsa-digital-discord-bot:v1
    container_name: discord-bot
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      USE_GLOBAL_COMMANDS: ${USE_GLOBAL_COMMANDS:-false}

      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL:-mongodb://root:example@mongo:27017/}

      CHICO_VERIFIED_ROLE_ID: ${CHICO_VERIFIED_ROLE_ID}
      CHICO_SIZE_CHANNEL_ID: ${CHICO_SIZE_CHANNEL_ID}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
volumes:
  postgres-data:
